/*
 * can_id_list.h
 */

#ifndef INC_CAN_ID_LIST_H_
#define INC_CAN_ID_LIST_H_

#define SAFE_STATE_ID 	0
#define ERROR_MSG_ID	1

/*
 * BMSMaster
 */

#define CANID_BMSMASTER_NODE 0x80
#define CANID_BMSMASTER_MASTERVOLTCURRTEMP 0x82
#define CANID_BMSMASTER_PCBSTHERM1TEMP 0x83
#define CANID_BMSMASTER_PCBSTHERM2TEMP 0x84
#define CANID_BMSMASTER_PCBSTHERM3TEMP 0x85
#define CANID_BMSMASTER_PCBSTHERM4TEMP 0x86
#define CANID_BMSMASTER_PCBSTHERM5TEMP 0x87
#define CANID_BMSMASTER_PCBSTHERM6TEMP 0x88
#define CANID_BMSMASTER_PCBSTHERM7TEMP 0x89
#define CANID_BMSMASTER_PCBSTHERM8TEMP 0x8A
#define CANID_BMSMASTER_PCBSTHERM9TEMP 0x8B
#define CANID_BMSMASTER_END 0x9F

/*
 * Charger1
 */

#define CANID_CHARGER1_STATIC_OUT 0x18FF50E5

/*
 * Charger2
 */

#define CANID_CHARGER2_STATIC_OUT 0x18FF50E7

/*
 * Charger3
 */

#define CANID_CHARGER3_STATIC_OUT 0x18FF50E8

/*
 * Converter
 */

#define CANID_CONVERTER_LOWVOLTCONVERTER_NODE 0x5C0
#define CANID_CONVERTER_LOWVOLTCONVERTER_END 0x5DF

/*
 * CoolingBack
 */

#define CANID_COOLINGBACK_NODE 0x4E0
#define CANID_COOLINGBACK_END 0x4FF

/*
 * CoolingLeft
 */

#define CANID_COOLINGLEFT_NODE 0x500
#define CANID_COOLINGLEFT_END 0x51F

/*
 * CoolingMotor
 */

#define CANID_COOLINGMOTOR_NODE 0x540
#define CANID_COOLINGMOTOR_END 0x55F

/*
 * CoolingRight
 */

#define CANID_COOLINGRIGHT_NODE 0x520
#define CANID_COOLINGRIGHT_END 0x53F

/*
 * Dashboard
 */

#define CANID_DASHBOARD_NODE 0x3E0
#define CANID_DASHBOARD_END 0x3FF

/*
 * EngineLeft
 */

#define CANID_ENGINELEFT_STATIC_EMCY 0xA6
#define CANID_ENGINELEFT_STATIC_TPDO1 0x1A6
#define CANID_ENGINELEFT_STATIC_TPDO2 0x2A6
#define CANID_ENGINELEFT_STATIC_NMT 0x726

/*
 * EngineRight
 */

#define CANID_ENGINERIGHT_STATIC_EMCY 0xA7
#define CANID_ENGINERIGHT_STATIC_TPDO1 0x1A7
#define CANID_ENGINERIGHT_STATIC_TPDO2 0x2A7
#define CANID_ENGINERIGHT_STATIC_NMT 0x727

/*
 * JETSON
 */

#define CANID_JETSON_STATIC_NODE 0x200
#define CANID_JETSON_STATIC_END 0x21F
#define CANID_JETSON_STATIC_ENGINELEFT_RPDO1 0x226
#define CANID_JETSON_STATIC_ENGINERIGHT_RPDO1 0x227

/*
 * LightsFL
 */

#define CANID_LIGHTSFL_NODE 0x760
#define CANID_LIGHTSFL_END 0x77F

/*
 * LightsFR
 */

#define CANID_LIGHTSFR_NODE 0x740
#define CANID_LIGHTSFR_END 0x75F

/*
 * LightsRL
 */

#define CANID_LIGHTSRL_NODE 0x7A0
#define CANID_LIGHTSRL_END 0x7BF

/*
 * LightsRR
 */

#define CANID_LIGHTSRR_NODE 0x780
#define CANID_LIGHTSRR_END 0x79F

/*
 * MPPT
 */

#define CANID_MPPT_NODE 0x460
#define CANID_MPPT_END 0x47F

/*
 * Pedals
 */

#define CANID_PEDALS_NODE 0x40
#define CANID_PEDALS_END 0x5F

/*
 * RCD
 */

#define CANID_RCD_STATIC_NODE 0xC0
#define CANID_RCD_STATIC_END 0xDF
#define CANID_RCD_STATIC_CHARGER1COMMS 0x1806E5F4
#define CANID_RCD_STATIC_CHARGER2COMMS 0x1806E7F4
#define CANID_RCD_STATIC_CHARGER3COMMS 0x1806E8F4

/*
 * SafeState
 */

#define CANID_SAFESTATE_NODE 0x0
#define CANID_SAFESTATE_END 0x1F

/*
 * SensorFL
 */

#define CANID_SENSORFL_NODE 0x660
#define CANID_SENSORFL_END 0x675

/*
 * SensorFR
 */

#define CANID_SENSORFR_NODE 0x640
#define CANID_SENSORFR_END 0x65F

/*
 * SensorRL
 */

#define CANID_SENSORRL_NODE 0x6A0
#define CANID_SENSORRL_END 0x6BF

/*
 * SensorRR
 */

#define CANID_SENSORRR_NODE 0x680
#define CANID_SENSORRR_END 0x69F

/*
 * SmallBMS
 */

#define CANID_SMALLBMS_NODE 0x360
#define CANID_SMALLBMS_END 0x37F

#endif /* INC_CAN_ID_LIST_H_ */
